### ISSUE TITLE
大哥继续更新啊，跟你学点技术

### ISSUE THREAD

**Issue by MrReN** [YusongWang/aptos-utils#2]

**Comment by peter209393** [comment]
好，继续更。后续的就麻烦一些了。

- 监听offer.自动套利一类的。
- 适配其他launchpad. 感兴趣可以一起写啊。

**Comment by MrReN** [comment]
大哥，您看我能帮上什么忙

**Comment by peter209393** [comment]
> 大哥，您看我能帮上什么忙

可以去对接lanuchpad. souf3 topaz 一类的。

不过目前Aptos没什么nft可以玩的。你可以对接一下，当练手了

**Comment by MrReN** [comment]
其实我对rust并不熟悉...还在学习rust当中

**Comment by MrReN** [comment]
哥，能不能问你个问题，bluemove的mint方法是从哪里找到的，并且abi传递的参数，您是如何知道对应要传递什么数据的？

**Comment by MrReN** [comment]
大哥，在buluemove.rs中，最后开抢，写个循环，这样会不停发送交易，gas能hold住吗？

**Comment by MrReN** [comment]
大哥，新年好。

**Comment by MrReN** [comment]
想请教下，在soffle3当中的public_sale_mint中的creator参数，这个是从哪里提前知道的，并且为什么和soffle3 nft页面当中显示的created地址不同呢

**Comment by peter209393** [comment]
> 想请教下，在soffle3当中的public_sale_mint中的creator参数，这个是从哪里提前知道的，并且为什么和soffle3 nft页面当中显示的created地址不同呢

不好意思最近阳了，才看到。

应该是一致的，created 地址类似于一个 solidity的合约地址。S3 预售开始快开始的时候去预售页面用F12看网络请求就可以。一般是一个404的 request 请求的是当前钱包资源，包含create地址。用于判断用户是否mint过（web按钮是否点亮）。用这个地址就可以。



> 大哥，新年好。

新年好



> 其实我对rust并不熟悉...还在学习rust当中

这个没关系，慢慢来。我也在学习rust。

**Comment by MrReN** [comment]
嗯嗯，还在学习中。
